apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk11
        env:
        - name: JENKINS_OPTS
          value: --prefix=/jenkins
        - name: SECRETS_DIR
          value: /etc/secrets
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: jenkins-creds
          mountPath: /etc/secrets
        resources:
          limits:
            memory: 2Gi
            cpu: 1
          requests:
            memory: 1Gi
            cpu: 0.5
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins
      - name: jenkins-creds
        secret:
          secretName: jenkins-creds
      securityContext:
        fsGroup: 1000